name: 📊 New Report
description: Used to set up a new report for GovA11y
title: <_ _ Name of Report _ _>
labels: [🤔 Unrefined, 📑 Report]
assignees:
  - theboatymcboatface
body:

  - type: input
    attributes:
      label: Question
      description: What specific question are you trying to answer with this report?
    validations:
      required: true

  - type: input
    attributes:
      label: Target Audience
      description: Who is the intended audience or end user of this report?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Input Options
      description: What parameters or options would you like to include in this report? (e.g., filter by domain, rule type, impact level, etc.)
      placeholder: \-[ ] domain
                    \-[ ] axe_id
    validations:
      required: true

  - type: textarea
    attributes:
      label: Report Output
      description: The columns this report will output
      placeholder: \-[ ] domain
                    \-[ ] axe_id
    validations:
      required: true


  - type: dropdown
    id: data_source
    attributes:
      label: Data Source
      description: Which primary data source will this report draw from? (Select one or more)
      multiple: true
      options:
        - 🌐 Accessibility Scans
        - 📊 Domain/URL Analysis
        - 🏢 Department/Organizational Structure
        - 🔍 Technology Stack Analysis
        - 📈 Complexity Calculations
        - 🏰 Security Assessments
        - 🪢 Summary Reports (Domain/Org/Tech)
        - ❔ Unknown/TBD/Other
    validations:
      required: true


  - type: textarea
    attributes:
      label: References
      description: Please provide any useful information or references related to this report (optional).
    validations:
      required: false